# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_name', models.CharField(max_length=20)),
                ('community_name', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=30)),
                ('snmp_version', models.CharField(max_length=2)),
                ('snmp_port', models.CharField(max_length=10)),
            ],
        ),
    ]
